# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StatuspageioMaintenanceCli < Formula
  desc "CLI tool to interact with statuspage.io and set maintenance on multiple pages at once"
  homepage "https://github.com/justinas-b/statuspage.io-maintenance-cli"
  version "0.0.5"

  on_macos do
    on_intel do
      url "https://github.com/justinas-b/statuspage.io-maintenance-cli/releases/download/v0.0.5/statuspage.io-maintenance-cli_Darwin_x86_64.tar.gz"
      sha256 "8f5b93a6bcea4d7f24b24681f29099890a74f3f63dd46f14768fd767ee07f2c7"

      def install
        bin.install "statuspage.io-maintenance-cli"
      end
    end
    on_arm do
      url "https://github.com/justinas-b/statuspage.io-maintenance-cli/releases/download/v0.0.5/statuspage.io-maintenance-cli_Darwin_arm64.tar.gz"
      sha256 "a68ea87fecabce9bda31dc414e210dacac73997fe07064d69c15cd328cf6111f"

      def install
        bin.install "statuspage.io-maintenance-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/justinas-b/statuspage.io-maintenance-cli/releases/download/v0.0.5/statuspage.io-maintenance-cli_Linux_x86_64.tar.gz"
        sha256 "5154731130dd05a916bc89158e61c5f561a69cdce61c14d93ec3fac30e16491e"

        def install
          bin.install "statuspage.io-maintenance-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/justinas-b/statuspage.io-maintenance-cli/releases/download/v0.0.5/statuspage.io-maintenance-cli_Linux_arm64.tar.gz"
        sha256 "feaa9f4e60c0672bf0cf69fc4ee415e38842ddee54f6f240aa4cf3ba02388292"

        def install
          bin.install "statuspage.io-maintenance-cli"
        end
      end
    end
  end

  def caveats
    <<~EOS
      ./statuspage.io-maintenance-cli -apiKeys abcd1234,efgh5678
    EOS
  end

  test do
    system "#{bin}/statuspage.io-maintenance-cli -h"
  end
end
