# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StatuspageioMaintenanceCli < Formula
  desc "CLI tool to interact with statuspage.io and set maintenance on multiple pages at once"
  homepage "https://github.com/justinas-b/statuspage.io-maintenance-cli"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/justinas-b/statuspage.io-maintenance-cli/releases/download/v0.0.2/statuspage.io-maintenance-cli_Darwin_x86_64.tar.gz"
      sha256 "ebe0186e481534c7dfc1d1de834be8c242475c04fecac6fab6bc4ce190d70636"

      def install
        bin.install "statuspage.io-maintenance-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/justinas-b/statuspage.io-maintenance-cli/releases/download/v0.0.2/statuspage.io-maintenance-cli_Darwin_arm64.tar.gz"
      sha256 "0eb6fc6c8ebb9e234ffb356054db94b17866cca69d60b5cd0f2f6c884db0c0ee"

      def install
        bin.install "statuspage.io-maintenance-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justinas-b/statuspage.io-maintenance-cli/releases/download/v0.0.2/statuspage.io-maintenance-cli_Linux_arm64.tar.gz"
      sha256 "6fc76992c825ad789b82da63fa6ade20cfbf21ac894acb89a42c3a6f0a73118a"

      def install
        bin.install "statuspage.io-maintenance-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/justinas-b/statuspage.io-maintenance-cli/releases/download/v0.0.2/statuspage.io-maintenance-cli_Linux_x86_64.tar.gz"
      sha256 "85f2780e1c04f0a78812ea3d9e7e0e87d839250361c6ce062eeb2e6bd4d9a375"

      def install
        bin.install "statuspage.io-maintenance-cli"
      end
    end
  end

  def caveats
    <<~EOS
      ./statuspage.io-maintenance-cli -apiKeys abcd1234,efgh5678
    EOS
  end

  test do
    system "#{bin}/statuspage.io-maintenance-cli -h"
  end
end
