# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StatuspageioMaintenanceCli < Formula
  desc "CLI tool to interact with statuspage.io and set maintenance on multiple pages at once"
  homepage "https://github.com/justinas-b/statuspage.io-maintenance-cli"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/justinas-b/statuspage.io-maintenance-cli/releases/download/v0.0.3/statuspage.io-maintenance-cli_Darwin_x86_64.tar.gz"
      sha256 "04867294ceae8a8acc7d623ac1102b808f7e5a97c779df14658f4e41006052ea"

      def install
        bin.install "statuspage.io-maintenance-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/justinas-b/statuspage.io-maintenance-cli/releases/download/v0.0.3/statuspage.io-maintenance-cli_Darwin_arm64.tar.gz"
      sha256 "53e81d6ca89e0e0651785c0f0a75dbd5b56d247f41b4335a6b002c8a2c85bcc9"

      def install
        bin.install "statuspage.io-maintenance-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justinas-b/statuspage.io-maintenance-cli/releases/download/v0.0.3/statuspage.io-maintenance-cli_Linux_arm64.tar.gz"
      sha256 "53121619296341b8161123d8a98cbe4d41ed23f0349db8c774589de6401d4a21"

      def install
        bin.install "statuspage.io-maintenance-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/justinas-b/statuspage.io-maintenance-cli/releases/download/v0.0.3/statuspage.io-maintenance-cli_Linux_x86_64.tar.gz"
      sha256 "deb427f084084c2d30c421f3483efb67fbbdeba833560369e280089f9e6b02a0"

      def install
        bin.install "statuspage.io-maintenance-cli"
      end
    end
  end

  def caveats
    <<~EOS
      ./statuspage.io-maintenance-cli -apiKeys abcd1234,efgh5678
    EOS
  end

  test do
    system "#{bin}/statuspage.io-maintenance-cli -h"
  end
end
